### PR TITLE
Featdbpsql

### PR DESCRIPTION
**Pull request by mblevu**
contribute relationships and merge.
ps. review as well

### CODE REVIEW

**Comment by sam-fsd** [comment]
The models are in one file. I thought we agreed to separate them into different files as earlier. Also some of the files that have been pushed are not supposed to be there such as pycache folder.

**Review by mblevu — COMMENTED** [review]
backend structure improved
frontend structure improved to simpley backend sync
added env to store secrets
gitignored relevant files

**Review by sam-fsd — COMMENTED** [review]
Good job with the models abstractions. Also there is an unfinished relationship defintion in the `Product` class. Since farmer has a relationship(One-to-Many) with a product, there should be a `farmer_id` _foreign key_ in the Product class. Necessary so as to show which farmer posted the product.

**Comment by mblevu** [comment]
changes added to recent push featinitapi branch

**Pull request closed without merging**
